### ISSUE TITLE
Price display with service fee.

### ISSUE THREAD

**Issue by clickonlite** [brownpapertickets/brown-paper-tickets-wordpress#16]
$75.00 ($78.62 w/service fee)

This seems like a more attractive way to display prices with the service fee option, if possible, like it does on the website.

**Comment by chantron** [comment]
Originally, this was how I was going to display prices by default. I don't remember why I decided not to but I don't see why this couldn't be an option. 

This wouldn't affect anything if you have the "include service fee" option selected. That is intended for prices that have "Service Fee: Included in Price" option set on Brown Paper Tickets. I'll make it so that you can select that option for each price rather than just all or nothing as it is now.

**Comment by chantron** [comment]
I've added this in 0.6.0 (fed2d281) which should now be available in the Wordpress repos. To include the Service Fee, just go to the event list when logged in as an admin and select "No" in the "Include Service Fee" select under the price level. If you have the "Include Service Fee" option set in the BPT Settings panel, that will override this setting.
