### ISSUE TITLE
Caching issues

### ISSUE THREAD

**Issue by razordaze** [brownpapertickets/brown-paper-tickets-wordpress#22]
Something's not quite right about the caching settings... 

Caching was set for 12 hours. An event scheduled for the 27th (and no other date) was showing up in the event list and calendar while caching was enabled. 

When caching was turned off, the past event would no longer appear. 

When caching was enabled, (for any value) the past event would re-appear. 

After clearing the cache, the past event would no longer appear, regardless of other caching settings.

Does the cache actually refresh at any interval?

**Comment by chantron** [comment]
That sounds like it might be that the filters which hide old/inactive events/dates not being applied to the cached data. I will investigate!

**Comment by chantron** [comment]
I've finally had some time to look into this but nothing stands out.

However, I do have a theory.

Here is what I suspect was happening:
* When the plugin first hit the BPT API, the event was live and it cached the event info.
* When the caching is turned off, the plugin goes straight to the BPT API to get the event info rather than grabbing the cached data. This time, the event wasn't live so it threw out the event data. Once you clear the cache, it will pull new event info from the BPT API.

As far as whether or not the cache is refreshed, I don't have any reason to suspect that it's failing to refresh.

Caching is handled by the [WordPress Transients API](http://codex.wordpress.org/Transients_API) and checks for the post's event info cache with `get_transient`[(docs)](http://codex.wordpress.org/Function_Reference/get_transient) which will return false if it has expired. I double checked that the transient's TTL was being set correctly and tested that the feed does indeed refresh after expiry (I set my cache to 1 minute).

I feel like this is enough to close the issue since
